# Generated by Django 3.2.18 on 2023-04-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managenotes', '0003_class_name_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=4),
        ),
    ]
