# Generated by Django 3.2.18 on 2023-04-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managenotes', '0004_alter_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
