# Generated by Django 3.2.18 on 2023-04-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managenotes', '0005_notes_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='name_computing',
            field=models.CharField(default='<django.db.models.fields.CharField>', max_length=4),
        ),
    ]
