# Generated by Django 3.2.18 on 2023-04-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managenotes', '0006_class_name_computing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name_computing',
            field=models.CharField(default='', max_length=4),
        ),
    ]
