# Generated by Django 3.2.18 on 2023-04-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managenotes', '0007_alter_class_name_computing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['name_computing']},
        ),
        migrations.AddField(
            model_name='notes',
            name='chapter_number_computing',
            field=models.CharField(default='', max_length=4),
        ),
    ]
