# Generated by Django 3.2.18 on 2023-04-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managenotes', '0009_remove_notes_chapter_number_computing'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
